### ISSUE TITLE
Make methods public or open

### ISSUE THREAD

**Issue by madhikarma** [ustwo/image-color-swift#8]
So that they can be accessible outside their module I.e. CocoaPods

Note. Use `open` instead for allowing subclassing / overriding if possible otherwise `public`

Note. after merging, tagged version and push to CocoaPods will be required

**Comment by danieladias** [comment]
What do you think in this case? I was going for public and not allowing subclassing only because I can't think of a use case :(

**Comment by madhikarma** [comment]
Recently discovered that extensions (maybe on Cocoa?) can't be made `open` which sort of makes sense so it might just be a case of `public` for this one

**Comment by danieladias** [comment]
@madhikarma I see. Thanks! 👍

**Comment by madhikarma** [comment]
As discussed seems like it's possible top `open` the individual methods in an extension (not the extension itself of course) though I'm not sure if static / class methods affect things...
